version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
    - ./data/dhis2-db-sierra-leone.sql:/dhis2-db-sierra-leone.sql
  web:
    image: dhis2/core:2.33.0
    volumes:
    - ./DHIS2_home/dhis.conf:/DHIS2_home/dhis.conf
    environment:
    - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    ports:
    - "8085:8080"
    depends_on:
    - db
